@baseurl = http://localhost:3000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMzc4MTE3YS05NjhlLTQ2ODAtOWQ2MC1lNzI0YWMyOTFjOTciLCJ1c2VybmFtZSI6InVzZXIyIiwiaWF0IjoxNzcyNjQ1NjYzLCJleHAiOjE3NzI2NDU3MjN9.vHOSp8exoVdy4bIBZFSM8uguY5BynT3umHBp2eUBM0Q

POST {{baseurl}}/auth/register
Content-Type: application/json

{
	"username": "user2",
	"email": "user2@email.com",
	"password": "user2"
}

###

POST {{baseurl}}/auth/login
Content-Type: application/json

{
	"email": "user2@email.com",
	"password": "user2"
}

###

POST {{baseurl}}/auth/profile
Authorization: Bearer {{token}}

###

POST {{baseurl}}/auth/refresh
Authorization: Bearer {{token}}